CONTIKI_PROJECT = os-only
all: $(CONTIKI_PROJECT)

CONTIKI = ../..

# Keep the project minimal: rely on $(CONTIKI_PROJECT).c only

# You can also pass V=1 to see full commands
include $(CONTIKI)/Makefile.include
